# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86c57f99fc9b047b85857bfe5970a3bb5d922e85225ff5c06c79adeede2dd94b7796b63d7e9581e741e839c9c6262661c7e52f3bae54f202c688873bcd528769

test:
  secret_key_base: 4caf15c0f043c42a63505c6026dcaa016fdf9146d577b4a96322021a517992268cd483e7fe77b5ee3d13fe262543e8206ba63125d941862200ed86040512420c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
